@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.dianping.cat.Cat#logRemoteCallClient(Context,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.dianping.cat.Cat"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_231963676 { 
   	label=dianping
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1054235340 { 
   	label=cat
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1171320324 { 
   	label=DefaultMetric
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMetric982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultMetric

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1714593488 { 
   	label=DefaultHeartbeat
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultHeartbeat982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultHeartbeat

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1808896656 { 
   	label=AbstractMessage
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractMessage982561799XXXaddData1808118735[
	label="+ addData()"
	style=filled
	fillcolor=white
	tooltip="AbstractMessage

&#10;		 add one or multiple key-value pairs to the message.&#10;		&#10;		 @param keyValuePairs key-value pairs like 'a=1&b=2&...'&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1827880093 { 
   	label=MessageIdFactory
	labeljust=l
	fillcolor=white
	style=filled
   
   MessageIdFactory982561799XXXgetNextId1808118735[
	label="+ getNextId()"
	style=filled
	fillcolor=white
	tooltip="MessageIdFactory

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_398883310 { 
   	label=DefaultTransaction
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultTransaction982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultTransaction

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_729580959 { 
   	label=Cat
	labeljust=l
	fillcolor=white
	style=filled
   
   Cat2002533913XXXcreateMessageId0[
	label="+ createMessageId()"
	style=filled
	fillcolor=white
	tooltip="Cat

null"
	fontcolor=darkgreen
];

Cat2002533913XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="Cat

null"
	fontcolor=darkgreen
];

Cat2002533913XXXlogRemoteCallClient1678783089[
	label="+ logRemoteCallClient()"
	style=filled
	fillcolor=white
	tooltip="Cat

&#10;		 logRemoteCallClient is used in rpc client&#10;		&#10;		 @param ctxctx is rpc context ,such as duboo context , please use rpc context implement Context&#10;		 @param domain domain is default, if use default config, the performance of server storage is bad。&#10;		"
	fontcolor=darkgreen
];

Cat2002533913XXXlogRemoteCallClient406701772[
	label="+ logRemoteCallClient()"
	style=filled
	fillcolor=white
	tooltip="Cat

&#10;		 logRemoteCallClient is used in rpc client&#10;		&#10;		 @param ctxctx is rpc context ,such as duboo context , please use rpc context implement Context&#10;		 @param domain domain is project name of rpc server name&#10;		"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_766785005 { 
   	label=DefaultMessageProducer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMessageProducer982561799XXXcreateMessageId0[
	label="+ createMessageId()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Create a new message id.&#10;		&#10;		 @return new message id&#10;		"
	fontcolor=darkgreen
];

DefaultMessageProducer982561799XXXcreateRpcServerId1808118735[
	label="+ createRpcServerId()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Create rpc server message id.&#10;		 \<p\>&#10;		 domain is the rpc server&#10;		&#10;		 @return new message id&#10;		"
	fontcolor=darkgreen
];

DefaultMessageProducer982561799XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Log an event in one shot.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		 @param status \"0\" means success, otherwise means error code&#10;		 @param nameValuePairs name value pairs in the format of \"a=1&b=2&...\"&#10;		"
	fontcolor=darkgreen
];

DefaultMessageProducer982561799XXXnewEvent2013066710[
	label="+ newEvent()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Create a new event with given type and name.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_773623139 { 
   	label=NullMessageProducer
	labeljust=l
	fillcolor=white
	style=filled
   
   NullMessageProducer982561799XXXcreateMessageId0[
	label="+ createMessageId()"
	style=filled
	fillcolor=white
	tooltip="NullMessageProducer

&#10;		 Create a new message id.&#10;		&#10;		 @return new message id&#10;		"
	fontcolor=darkgreen
];

NullMessageProducer982561799XXXcreateRpcServerId1808118735[
	label="+ createRpcServerId()"
	style=filled
	fillcolor=white
	tooltip="NullMessageProducer

&#10;		 Create rpc server message id.&#10;		 \<p\>&#10;		 domain is the rpc server&#10;		&#10;		 @return new message id&#10;		"
	fontcolor=darkgreen
];

NullMessageProducer982561799XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="NullMessageProducer

&#10;		 Log an event in one shot.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		 @param status \"0\" means success, otherwise means error code&#10;		 @param nameValuePairs name value pairs in the format of \"a=1&b=2&...\"&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_786603214 { 
   	label=DefaultEvent
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultEvent982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultEvent

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_800332665 { 
   	label=DefaultTrace
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultTrace982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultTrace

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Cat2002533913XXXcreateMessageId0 -> DefaultMessageProducer982561799XXXcreateMessageId0;
Cat2002533913XXXcreateMessageId0 -> NullMessageProducer982561799XXXcreateMessageId0;
Cat2002533913XXXlogEvent2012146208 -> DefaultMessageProducer982561799XXXlogEvent2012146208;
Cat2002533913XXXlogEvent2012146208 -> NullMessageProducer982561799XXXlogEvent2012146208;
Cat2002533913XXXlogRemoteCallClient1678783089 -> Cat2002533913XXXlogRemoteCallClient406701772;
Cat2002533913XXXlogRemoteCallClient406701772 -> Cat2002533913XXXcreateMessageId0;
Cat2002533913XXXlogRemoteCallClient406701772 -> Cat2002533913XXXlogEvent2012146208;
Cat2002533913XXXlogRemoteCallClient406701772 -> DefaultMessageProducer982561799XXXcreateRpcServerId1808118735;
Cat2002533913XXXlogRemoteCallClient406701772 -> NullMessageProducer982561799XXXcreateRpcServerId1808118735;
DefaultMessageProducer982561799XXXcreateRpcServerId1808118735 -> MessageIdFactory982561799XXXgetNextId1808118735;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> AbstractMessage982561799XXXaddData1808118735;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultEvent982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultHeartbeat982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultMessageProducer982561799XXXnewEvent2013066710;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultMetric982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultTrace982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultTransaction982561799XXXcomplete0;
NullMessageProducer982561799XXXcreateRpcServerId1808118735 -> NullMessageProducer982561799XXXcreateMessageId0;
    
}
@enduml