@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.dianping.cat.Cat#logEvent(String,String,String,String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.dianping.cat.Cat"
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_231963676 { 
   	label=dianping
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1054235340 { 
   	label=cat
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_109443359 { 
   	label=LocalEventService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalEventService324698713XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalEventService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1171320324 { 
   	label=DefaultMetric
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMetric982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultMetric

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1201051041 { 
   	label=LocalHeartbeatService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalHeartbeatService1256167671XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalHeartbeatService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1206261271 { 
   	label=UtilizationReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   UtilizationReportBuilder272944022XXXbuildHourlyTask1730104472[
	label="+ buildHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="UtilizationReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1235525822 { 
   	label=NullMessageManager
	labeljust=l
	fillcolor=white
	style=filled
   
   NullMessageManager982561799XXXadd1675388953[
	label="+ add()"
	style=filled
	fillcolor=white
	tooltip="NullMessageManager

null"
	fontcolor=darkgreen
];

NullMessageManager982561799XXXend485852482[
	label="+ end()"
	style=filled
	fillcolor=white
	tooltip="NullMessageManager

&#10;		 Be triggered when a transaction ends, whatever it's the root transaction or nested transaction. However, if it's&#10;		 the root transaction then it will be flushed to back-end CAT server asynchronously.&#10;		 \<p\>&#10;		&#10;		 @param transaction&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1257165599 { 
   	label=BusinessReportGroupService
	labeljust=l
	fillcolor=white
	style=filled
   
   BusinessReportGroupService792960521XXXprepareDatas477497297[
	label="+ prepareDatas()"
	style=filled
	fillcolor=white
	tooltip="BusinessReportGroupService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1280963523 { 
   	label=RouterConfigHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   RouterConfigHandler938245874XXXbuildRouterConfig950324557[
	label="+ buildRouterConfig()"
	style=filled
	fillcolor=white
	tooltip="RouterConfigHandler

null"
	fontcolor=darkgreen
];

RouterConfigHandler938245874XXXupdateRouterConfig2122702[
	label="+ updateRouterConfig()"
	style=filled
	fillcolor=white
	tooltip="RouterConfigHandler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1307296888 { 
   	label=StorageReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   StorageReportBuilder1718956562XXXinitialize0[
	label="+ initialize()"
	style=filled
	fillcolor=white
	tooltip="StorageReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1309613838 { 
   	label=CachedBusinessReportService
	labeljust=l
	fillcolor=white
	style=filled
   
   CachedBusinessReportService798456449XXXqueryBusinessReport950324557[
	label="+ queryBusinessReport()"
	style=filled
	fillcolor=white
	tooltip="CachedBusinessReportService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1362586179 { 
   	label=DatabaseParser
	labeljust=l
	fillcolor=white
	style=filled
   
   DatabaseParser925500459XXXshowErrorCon0[
	label="+ showErrorCon()"
	style=filled
	fillcolor=white
	tooltip="DatabaseParser

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1382457875 { 
   	label=SenderManager
	labeljust=l
	fillcolor=white
	style=filled
   
   SenderManager1732819881XXXsendAlert932354681[
	label="+ sendAlert()"
	style=filled
	fillcolor=white
	tooltip="SenderManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_146084160 { 
   	label=FailureSummaryBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   FailureSummaryBuilder655011407XXXgenerateModel950324557[
	label="+ generateModel()"
	style=filled
	fillcolor=white
	tooltip="FailureSummaryBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1475384853 { 
   	label=StorageAnalyzer
	labeljust=l
	fillcolor=white
	style=filled
   
   StorageAnalyzer1601504328XXXdoCheckpoint64711720[
	label="+ doCheckpoint()"
	style=filled
	fillcolor=white
	tooltip="StorageAnalyzer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1536005449 { 
   	label=HeartbeatAlert
	labeljust=l
	fillcolor=white
	style=filled
   
   HeartbeatAlert1714023003XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="HeartbeatAlert

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1577120129 { 
   	label=LocalStateService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalStateService1634735970XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalStateService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1631429255 { 
   	label=ExternalInfoBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   ExternalInfoBuilder119244091XXXbuildExceptionInfoOnGraph693934916[
	label="+ buildExceptionInfoOnGraph()"
	style=filled
	fillcolor=white
	tooltip="ExternalInfoBuilder

null"
	fontcolor=darkgreen
];

ExternalInfoBuilder119244091XXXbuildNodeExceptionInfo1055667658[
	label="+ buildNodeExceptionInfo()"
	style=filled
	fillcolor=white
	tooltip="ExternalInfoBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1650349353 { 
   	label=RouterConfigBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   RouterConfigBuilder1370596043XXXbuildDailyTask1730104472[
	label="+ buildDailyTask()"
	style=filled
	fillcolor=white
	tooltip="RouterConfigBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1663430405 { 
   	label=TransactionAlert
	labeljust=l
	fillcolor=white
	style=filled
   
   TransactionAlert149352775XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="TransactionAlert

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1714593488 { 
   	label=DefaultHeartbeat
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultHeartbeat982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultHeartbeat

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1723658738 { 
   	label=DefaultMessageManager
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMessageManager982561799XXXadd1675388953[
	label="+ add()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageManager

null"
	fontcolor=darkgreen
];

DefaultMessageManager982561799XXXend485852482[
	label="+ end()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageManager

&#10;		 Be triggered when a transaction ends, whatever it's the root transaction or nested transaction. However, if it's&#10;		 the root transaction then it will be flushed to back-end CAT server asynchronously.&#10;		 \<p\>&#10;		&#10;		 @param transaction&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1757278497 { 
   	label=LocalCrossService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalCrossService218981043XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalCrossService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1760607835 { 
   	label=BusinessAlert
	labeljust=l
	fillcolor=white
	style=filled
   
   BusinessAlert792960521XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="BusinessAlert

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1808896656 { 
   	label=AbstractMessage
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractMessage982561799XXXaddData1808118735[
	label="+ addData()"
	style=filled
	fillcolor=white
	tooltip="AbstractMessage

&#10;		 add one or multiple key-value pairs to the message.&#10;		&#10;		 @param keyValuePairs key-value pairs like 'a=1&b=2&...'&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_1820719436 { 
   	label=SummaryBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   SummaryBuilder655011407XXXgenerateHtml950324557[
	label="+ generateHtml()"
	style=filled
	fillcolor=white
	tooltip="SummaryBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1824915805 { 
   	label=DefaultReportManager
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultReportManager1062576471XXXstoreHourlyReports1893863326[
	label="+ storeHourlyReports()"
	style=filled
	fillcolor=white
	tooltip="DefaultReportManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1842262706 { 
   	label=AbstractMessageAnalyzer
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractMessageAnalyzer468824849XXXdoCheckpoint64711720[
	label="+ doCheckpoint()"
	style=filled
	fillcolor=white
	tooltip="AbstractMessageAnalyzer

null"
	fontcolor=darkgreen
];

AbstractMessageAnalyzer468824849XXXgetReport1808118735[
	label="+ getReport()"
	style=filled
	fillcolor=white
	tooltip="AbstractMessageAnalyzer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1877057340 { 
   	label=DependencyReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   DependencyReportBuilder2009130766XXXbuildHourlyTask1730104472[
	label="+ buildHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="DependencyReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_18792960 { 
   	label=DependencyReloadTask
	labeljust=l
	fillcolor=white
	style=filled
   
   DependencyReloadTask717202409XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="DependencyReloadTask

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1924001473 { 
   	label=AbstractReportService
	labeljust=l
	fillcolor=white
	style=filled
   
   AbstractReportService1722581904XXXqueryAllDomainNames988136651[
	label="+ queryAllDomainNames()"
	style=filled
	fillcolor=white
	tooltip="AbstractReportService

null"
	fontcolor=darkgreen
];

AbstractReportService1722581904XXXqueryHourlyReport660492363[
	label="+ queryHourlyReport()"
	style=filled
	fillcolor=white
	tooltip="AbstractReportService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1931760353 { 
   	label=LocalTransactionService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalTransactionService62328171XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalTransactionService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1944383941 { 
   	label=BaseHistoricalModelService
	labeljust=l
	fillcolor=white
	style=filled
   
   BaseHistoricalModelService1722581904XXXinvoke1120842566[
	label="+ invoke()"
	style=filled
	fillcolor=white
	tooltip="BaseHistoricalModelService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2031921028 { 
   	label=DefaultRemoteServersUpdater
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultRemoteServersUpdater1539190358XXXbuildServers2122702[
	label="+ buildServers()"
	style=filled
	fillcolor=white
	tooltip="DefaultRemoteServersUpdater

null"
	fontcolor=darkgreen
];

DefaultRemoteServersUpdater1539190358XXXqueryStateReport949119647[
	label="+ queryStateReport()"
	style=filled
	fillcolor=white
	tooltip="DefaultRemoteServersUpdater

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2036387711 { 
   	label=LocalDependencyService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalDependencyService1423065972XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalDependencyService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_223834753 { 
   	label=LocalProblemService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalProblemService988840148XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalProblemService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_239955154 { 
   	label=ReportFacade
	labeljust=l
	fillcolor=white
	style=filled
   
   ReportFacade1539190358XXXbuilderReport2599333[
	label="+ builderReport()"
	style=filled
	fillcolor=white
	tooltip="ReportFacade

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_245863904 { 
   	label=DomainFilter
	labeljust=l
	fillcolor=white
	style=filled
   
   DomainFilter1539123510XXXdoFilter1247943405[
	label="+ doFilter()"
	style=filled
	fillcolor=white
	tooltip="DomainFilter

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_254873948 { 
   	label=SendExecutor
	labeljust=l
	fillcolor=white
	style=filled
   
   SendExecutor502410565XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="SendExecutor

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_343873951 { 
   	label=HeavyReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   HeavyReportBuilder1211085553XXXbuildHourlyTask1730104472[
	label="+ buildHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="HeavyReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_367749253 { 
   	label=ProjectUpdateTask
	labeljust=l
	fillcolor=white
	style=filled
   
   ProjectUpdateTask1509455828XXXdeleteUnusedDomainInfo0[
	label="+ deleteUnusedDomainInfo()"
	style=filled
	fillcolor=white
	tooltip="ProjectUpdateTask

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_398883310 { 
   	label=DefaultTransaction
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultTransaction982561799XXXaddChild1675388953[
	label="+ addChild()"
	style=filled
	fillcolor=white
	tooltip="DefaultTransaction

&#10;		 Add one nested child message to current transaction.&#10;		&#10;		 @param message to be added&#10;		"
	fontcolor=darkgreen
];

DefaultTransaction982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultTransaction

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_417579689 { 
   	label=LocalBusinessService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalBusinessService798456449XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalBusinessService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_445911714 { 
   	label=StorageReportService
	labeljust=l
	fillcolor=white
	style=filled
   
   StorageReportService1718956562XXXqueryAllIds1330012304[
	label="+ queryAllIds()"
	style=filled
	fillcolor=white
	tooltip="StorageReportService

null"
	fontcolor=darkgreen
];

StorageReportService1718956562XXXqueryHourlyReport660492363[
	label="+ queryHourlyReport()"
	style=filled
	fillcolor=white
	tooltip="StorageReportService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_48527499 { 
   	label=RecoveryAnnouncer
	labeljust=l
	fillcolor=white
	style=filled
   
   RecoveryAnnouncer502410565XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="RecoveryAnnouncer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_502410565 { 
   	label=AlertManager
	labeljust=l
	fillcolor=white
	style=filled
   
   AlertManager1678305542XXXaddAlert313035839[
	label="+ addAlert()"
	style=filled
	fillcolor=white
	tooltip="AlertManager

null"
	fontcolor=darkgreen
];

AlertManager1678305542XXXisSuspend107927658[
	label="+ isSuspend()"
	style=filled
	fillcolor=white
	tooltip="AlertManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_56342005 { 
   	label=BaseRuleConfigManager
	labeljust=l
	fillcolor=white
	style=filled
   
   BaseRuleConfigManager1801461189XXXqueryConfigs1808118735[
	label="+ queryConfigs()"
	style=filled
	fillcolor=white
	tooltip="BaseRuleConfigManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_609461575 { 
   	label=StatusUpdateTask
	labeljust=l
	fillcolor=white
	style=filled
   
   StatusUpdateTask1020536473XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="StatusUpdateTask

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_622830674 { 
   	label=BusinessGraphCreator
	labeljust=l
	fillcolor=white
	style=filled
   
   BusinessGraphCreator669448218XXXbuildGraphByDomain988136651[
	label="+ buildGraphByDomain()"
	style=filled
	fillcolor=white
	tooltip="BusinessGraphCreator

null"
	fontcolor=darkgreen
];

BusinessGraphCreator669448218XXXbuildGraphByTag988136651[
	label="+ buildGraphByTag()"
	style=filled
	fillcolor=white
	tooltip="BusinessGraphCreator

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_642047153 { 
   	label=TransactionAnalyzer
	labeljust=l
	fillcolor=white
	style=filled
   
   TransactionAnalyzer976050789XXXgetReport1808118735[
	label="+ getReport()"
	style=filled
	fillcolor=white
	tooltip="TransactionAnalyzer

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_647801249 { 
   	label=StateBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   StateBuilder783603927XXXbuildStateMessage2028467489[
	label="+ buildStateMessage()"
	style=filled
	fillcolor=white
	tooltip="StateBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_653325837 { 
   	label=EventAlert
	labeljust=l
	fillcolor=white
	style=filled
   
   EventAlert1946561597XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="EventAlert

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_661391485 { 
   	label=ServiceReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   ServiceReportBuilder1271214333XXXbuildHourlyTask1730104472[
	label="+ buildHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="ServiceReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_729580959 { 
   	label=Cat
	labeljust=l
	fillcolor=white
	style=filled
   
   Cat2002533913XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="Cat

null"
	penwidth=4
	fontcolor=darkgreen
];

Cat2002533913XXXlogRemoteCallClient1678783089[
	label="+ logRemoteCallClient()"
	style=filled
	fillcolor=white
	tooltip="Cat

&#10;		 logRemoteCallClient is used in rpc client&#10;		&#10;		 @param ctxctx is rpc context ,such as duboo context , please use rpc context implement Context&#10;		 @param domain domain is default, if use default config, the performance of server storage is bad。&#10;		"
	fontcolor=darkgreen
];

Cat2002533913XXXlogRemoteCallClient406701772[
	label="+ logRemoteCallClient()"
	style=filled
	fillcolor=white
	tooltip="Cat

&#10;		 logRemoteCallClient is used in rpc client&#10;		&#10;		 @param ctxctx is rpc context ,such as duboo context , please use rpc context implement Context&#10;		 @param domain domain is project name of rpc server name&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_729725148 { 
   	label=HeartbeatRuleConfigManager
	labeljust=l
	fillcolor=white
	style=filled
   
   HeartbeatRuleConfigManager1714023003XXXqueryConfigsByDomain1808118735[
	label="+ queryConfigsByDomain()"
	style=filled
	fillcolor=white
	tooltip="HeartbeatRuleConfigManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_74581065 { 
   	label=JarReportBuilder
	labeljust=l
	fillcolor=white
	style=filled
   
   JarReportBuilder215783325XXXbuildHourlyTask1730104472[
	label="+ buildHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="JarReportBuilder

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_761553471 { 
   	label=LocalTopService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalTopService1235043614XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalTopService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_766785005 { 
   	label=DefaultMessageProducer
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultMessageProducer982561799XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Log an event in one shot.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		 @param status \"0\" means success, otherwise means error code&#10;		 @param nameValuePairs name value pairs in the format of \"a=1&b=2&...\"&#10;		"
	fontcolor=darkgreen
];

DefaultMessageProducer982561799XXXnewEvent2013066710[
	label="+ newEvent()"
	style=filled
	fillcolor=white
	tooltip="DefaultMessageProducer

&#10;		 Create a new event with given type and name.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_773623139 { 
   	label=NullMessageProducer
	labeljust=l
	fillcolor=white
	style=filled
   
   NullMessageProducer982561799XXXlogEvent2012146208[
	label="+ logEvent()"
	style=filled
	fillcolor=white
	tooltip="NullMessageProducer

&#10;		 Log an event in one shot.&#10;		&#10;		 @param type event type&#10;		 @param name event name&#10;		 @param status \"0\" means success, otherwise means error code&#10;		 @param nameValuePairs name value pairs in the format of \"a=1&b=2&...\"&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_778883053 { 
   	label=DefaultReportBucketManager
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultReportBucketManager1062576471XXXclearOldReports0[
	label="+ clearOldReports()"
	style=filled
	fillcolor=white
	tooltip="DefaultReportBucketManager

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_784414652 { 
   	label=AlertSummaryExecutor
	labeljust=l
	fillcolor=white
	style=filled
   
   AlertSummaryExecutor1478910607XXXexecute1368930904[
	label="+ execute()"
	style=filled
	fillcolor=white
	tooltip="AlertSummaryExecutor

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_786603214 { 
   	label=DefaultEvent
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultEvent982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultEvent

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_7896541 { 
   	label=ExceptionAlert
	labeljust=l
	fillcolor=white
	style=filled
   
   ExceptionAlert433294088XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="ExceptionAlert

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_800332665 { 
   	label=DefaultTrace
	labeljust=l
	fillcolor=white
	style=filled
   
   DefaultTrace982561799XXXcomplete0[
	label="+ complete()"
	style=filled
	fillcolor=white
	tooltip="DefaultTrace

&#10;		 Complete the message construction.&#10;		"
	fontcolor=darkgreen
];
} 

subgraph cluster_814881791 { 
   	label=LocalStorageService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalStorageService233610488XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalStorageService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_82053174 { 
   	label=StateDelegate
	labeljust=l
	fillcolor=white
	style=filled
   
   StateDelegate2142459634XXXcreateHourlyTask1477821179[
	label="+ createHourlyTask()"
	style=filled
	fillcolor=white
	tooltip="StateDelegate

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_861740201 { 
   	label=Handler
	labeljust=l
	fillcolor=white
	style=filled
   
   Handler1913663259XXXhandleOutbound1678783089[
	label="+ handleOutbound()"
	style=filled
	fillcolor=white
	tooltip="Handler

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_872551164 { 
   	label=BaseCompositeModelService
	labeljust=l
	fillcolor=white
	style=filled
   
   BaseCompositeModelService1722581904XXXinvoke1120842566[
	label="+ invoke()"
	style=filled
	fillcolor=white
	tooltip="BaseCompositeModelService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_950088597 { 
   	label=LocalMatrixService
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalMatrixService408516610XXXbuildReport1340167043[
	label="+ buildReport()"
	style=filled
	fillcolor=white
	tooltip="LocalMatrixService

null"
	fontcolor=darkgreen
];
} 
} 
} 

subgraph cluster_840542049 { 
   	label=unidal
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1272011271 { 
   	label=cat
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1006478529 { 
   	label=LocalIndex
	labeljust=l
	fillcolor=white
	style=filled
   
   LocalIndex663634356XXXfind563954530[
	label="+ find()"
	style=filled
	fillcolor=white
	tooltip="LocalIndex

null"
	fontcolor=darkgreen
];

LocalIndex663634356XXXmap1554402252[
	label="+ map()"
	style=filled
	fillcolor=white
	tooltip="LocalIndex

null"
	fontcolor=darkgreen
];

LocalIndex663634356XXXmaps1951155058[
	label="+ maps()"
	style=filled
	fillcolor=white
	tooltip="LocalIndex

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1467515670 { 
   	label=SegmentCache
	labeljust=l
	fillcolor=white
	style=filled
   
   SegmentCache348280493XXXfindOrCreateNextSegment3327612[
	label="+ findOrCreateNextSegment()"
	style=filled
	fillcolor=white
	tooltip="SegmentCache

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AbstractMessageAnalyzer468824849XXXdoCheckpoint64711720 -> StorageAnalyzer1601504328XXXdoCheckpoint64711720;
AbstractMessageAnalyzer468824849XXXgetReport1808118735 -> TransactionAnalyzer976050789XXXgetReport1808118735;
AbstractReportService1722581904XXXqueryAllDomainNames988136651 -> Cat2002533913XXXlogEvent2012146208;
AbstractReportService1722581904XXXqueryHourlyReport660492363 -> StorageReportService1718956562XXXqueryHourlyReport660492363;
AlertManager1678305542XXXaddAlert313035839 -> Cat2002533913XXXlogEvent2012146208;
AlertManager1678305542XXXisSuspend107927658 -> Cat2002533913XXXlogEvent2012146208;
AlertSummaryExecutor1478910607XXXexecute1368930904 -> SenderManager1732819881XXXsendAlert932354681;
BaseCompositeModelService1722581904XXXinvoke1120842566 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
BaseCompositeModelService1722581904XXXinvoke1120842566 -> Cat2002533913XXXlogEvent2012146208;
BaseHistoricalModelService1722581904XXXinvoke1120842566 -> Cat2002533913XXXlogEvent2012146208;
BaseRuleConfigManager1801461189XXXqueryConfigs1808118735 -> Cat2002533913XXXlogEvent2012146208;
BusinessAlert792960521XXXrun0 -> BusinessReportGroupService792960521XXXprepareDatas477497297;
BusinessGraphCreator669448218XXXbuildGraphByDomain988136651 -> CachedBusinessReportService798456449XXXqueryBusinessReport950324557;
BusinessGraphCreator669448218XXXbuildGraphByTag988136651 -> CachedBusinessReportService798456449XXXqueryBusinessReport950324557;
BusinessReportGroupService792960521XXXprepareDatas477497297 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
CachedBusinessReportService798456449XXXqueryBusinessReport950324557 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Cat2002533913XXXlogEvent2012146208 -> DefaultMessageProducer982561799XXXlogEvent2012146208;
Cat2002533913XXXlogEvent2012146208 -> NullMessageProducer982561799XXXlogEvent2012146208;
Cat2002533913XXXlogRemoteCallClient1678783089 -> Cat2002533913XXXlogRemoteCallClient406701772;
Cat2002533913XXXlogRemoteCallClient406701772 -> Cat2002533913XXXlogEvent2012146208;
DatabaseParser925500459XXXshowErrorCon0 -> Cat2002533913XXXlogEvent2012146208;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> AbstractMessage982561799XXXaddData1808118735;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultEvent982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultHeartbeat982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultMessageProducer982561799XXXnewEvent2013066710;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultMetric982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultTrace982561799XXXcomplete0;
DefaultMessageProducer982561799XXXlogEvent2012146208 -> DefaultTransaction982561799XXXcomplete0;
DefaultRemoteServersUpdater1539190358XXXbuildServers2122702 -> DefaultRemoteServersUpdater1539190358XXXqueryStateReport949119647;
DefaultRemoteServersUpdater1539190358XXXqueryStateReport949119647 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
DefaultReportBucketManager1062576471XXXclearOldReports0 -> Cat2002533913XXXlogEvent2012146208;
DefaultReportManager1062576471XXXstoreHourlyReports1893863326 -> StateDelegate2142459634XXXcreateHourlyTask1477821179;
DefaultTrace982561799XXXcomplete0 -> DefaultMessageManager982561799XXXadd1675388953;
DefaultTrace982561799XXXcomplete0 -> NullMessageManager982561799XXXadd1675388953;
DefaultTransaction982561799XXXcomplete0 -> DefaultEvent982561799XXXcomplete0;
DefaultTransaction982561799XXXcomplete0 -> DefaultMessageManager982561799XXXend485852482;
DefaultTransaction982561799XXXcomplete0 -> DefaultTransaction982561799XXXaddChild1675388953;
DefaultTransaction982561799XXXcomplete0 -> NullMessageManager982561799XXXend485852482;
DependencyReloadTask717202409XXXrun0 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
DependencyReportBuilder2009130766XXXbuildHourlyTask1730104472 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
DomainFilter1539123510XXXdoFilter1247943405 -> Cat2002533913XXXlogEvent2012146208;
EventAlert1946561597XXXrun0 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
ExceptionAlert433294088XXXrun0 -> AlertManager1678305542XXXaddAlert313035839;
ExceptionAlert433294088XXXrun0 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
ExternalInfoBuilder119244091XXXbuildExceptionInfoOnGraph693934916 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
ExternalInfoBuilder119244091XXXbuildNodeExceptionInfo1055667658 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
FailureSummaryBuilder655011407XXXgenerateModel950324557 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler119244091XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler1283269275XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler1436966209XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler1666839493XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler187541347XXXhandleOutbound1678783089 -> AlertSummaryExecutor1478910607XXXexecute1368930904;
Handler1913663259XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler1913663259XXXhandleOutbound1678783089 -> StateBuilder783603927XXXbuildStateMessage2028467489;
Handler535922750XXXhandleOutbound1678783089 -> RouterConfigHandler938245874XXXupdateRouterConfig2122702;
Handler630999377XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler630999377XXXhandleOutbound1678783089 -> Cat2002533913XXXlogEvent2012146208;
Handler740287836XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler752087618XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler766746018XXXhandleOutbound1678783089 -> SenderManager1732819881XXXsendAlert932354681;
Handler768263112XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler768781446XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler770737888XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler783603927XXXhandleOutbound1678783089 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
Handler783603927XXXhandleOutbound1678783089 -> StateBuilder783603927XXXbuildStateMessage2028467489;
HeartbeatAlert1714023003XXXrun0 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
HeartbeatRuleConfigManager1714023003XXXqueryConfigsByDomain1808118735 -> Cat2002533913XXXlogEvent2012146208;
HeavyReportBuilder1211085553XXXbuildHourlyTask1730104472 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
JarReportBuilder215783325XXXbuildHourlyTask1730104472 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
LocalBusinessService798456449XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalCrossService218981043XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalDependencyService1423065972XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalEventService324698713XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalHeartbeatService1256167671XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalIndex663634356XXXfind563954530 -> SegmentCache348280493XXXfindOrCreateNextSegment3327612;
LocalIndex663634356XXXmap1554402252 -> Cat2002533913XXXlogEvent2012146208;
LocalIndex663634356XXXmaps1951155058 -> LocalIndex663634356XXXmap1554402252;
LocalMatrixService408516610XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalProblemService988840148XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalStateService1634735970XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalStorageService233610488XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalTopService1235043614XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
LocalTransactionService62328171XXXbuildReport1340167043 -> AbstractMessageAnalyzer468824849XXXgetReport1808118735;
ProjectUpdateTask1509455828XXXdeleteUnusedDomainInfo0 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
ProjectUpdateTask1509455828XXXdeleteUnusedDomainInfo0 -> Cat2002533913XXXlogEvent2012146208;
RecoveryAnnouncer502410565XXXrun0 -> SenderManager1732819881XXXsendAlert932354681;
ReportFacade1539190358XXXbuilderReport2599333 -> RouterConfigBuilder1370596043XXXbuildDailyTask1730104472;
ReportFacade1539190358XXXbuilderReport2599333 -> ServiceReportBuilder1271214333XXXbuildHourlyTask1730104472;
RouterConfigBuilder1370596043XXXbuildDailyTask1730104472 -> RouterConfigHandler938245874XXXbuildRouterConfig950324557;
RouterConfigHandler938245874XXXbuildRouterConfig950324557 -> Cat2002533913XXXlogEvent2012146208;
RouterConfigHandler938245874XXXupdateRouterConfig2122702 -> RouterConfigHandler938245874XXXbuildRouterConfig950324557;
SegmentCache348280493XXXfindOrCreateNextSegment3327612 -> Cat2002533913XXXlogEvent2012146208;
SendExecutor502410565XXXrun0 -> SenderManager1732819881XXXsendAlert932354681;
SenderManager1732819881XXXsendAlert932354681 -> Cat2002533913XXXlogEvent2012146208;
ServiceReportBuilder1271214333XXXbuildHourlyTask1730104472 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
StateBuilder783603927XXXbuildStateMessage2028467489 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
StateDelegate2142459634XXXcreateHourlyTask1477821179 -> DefaultReportBucketManager1062576471XXXclearOldReports0;
StatusUpdateTask1020536473XXXrun0 -> Cat2002533913XXXlogEvent2012146208;
StorageAnalyzer1601504328XXXdoCheckpoint64711720 -> DatabaseParser925500459XXXshowErrorCon0;
StorageReportBuilder1718956562XXXinitialize0 -> StorageReportService1718956562XXXqueryAllIds1330012304;
StorageReportService1718956562XXXqueryAllIds1330012304 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
StorageReportService1718956562XXXqueryHourlyReport660492363 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
SummaryBuilder655011407XXXgenerateHtml950324557 -> FailureSummaryBuilder655011407XXXgenerateModel950324557;
TransactionAlert149352775XXXrun0 -> BaseCompositeModelService1722581904XXXinvoke1120842566;
TransactionAnalyzer976050789XXXgetReport1808118735 -> Cat2002533913XXXlogEvent2012146208;
UtilizationReportBuilder272944022XXXbuildHourlyTask1730104472 -> AbstractReportService1722581904XXXqueryAllDomainNames988136651;
    
}
@enduml